//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTWebAPI.UDIBroker {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fis.it.udi/UDIBroker", ConfigurationName="UDIBroker.wsBinRoutingSoap")]
    public interface wsBinRoutingSoap {
        
        // CODEGEN: Generating message contract since element name transaction from namespace http://fis.it.udi/UDIBroker is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://fis.it.udi/UDIBroker/ProcessByAcct", ReplyAction="*")]
        BTWebAPI.UDIBroker.ProcessByAcctResponse ProcessByAcct(BTWebAPI.UDIBroker.ProcessByAcctRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fis.it.udi/UDIBroker/ProcessByAcct", ReplyAction="*")]
        System.Threading.Tasks.Task<BTWebAPI.UDIBroker.ProcessByAcctResponse> ProcessByAcctAsync(BTWebAPI.UDIBroker.ProcessByAcctRequest request);
        
        // CODEGEN: Generating message contract since element name transaction from namespace http://fis.it.udi/UDIBroker is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://fis.it.udi/UDIBroker/ProcessByBin", ReplyAction="*")]
        BTWebAPI.UDIBroker.ProcessByBinResponse ProcessByBin(BTWebAPI.UDIBroker.ProcessByBinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fis.it.udi/UDIBroker/ProcessByBin", ReplyAction="*")]
        System.Threading.Tasks.Task<BTWebAPI.UDIBroker.ProcessByBinResponse> ProcessByBinAsync(BTWebAPI.UDIBroker.ProcessByBinRequest request);
        
        // CODEGEN: Generating message contract since element name Credentials from namespace http://fis.it.udi/UDIBroker is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://fis.it.udi/UDIBroker/Login", ReplyAction="*")]
        BTWebAPI.UDIBroker.LoginResponse Login(BTWebAPI.UDIBroker.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fis.it.udi/UDIBroker/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<BTWebAPI.UDIBroker.LoginResponse> LoginAsync(BTWebAPI.UDIBroker.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name Credentials from namespace http://fis.it.udi/UDIBroker is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://fis.it.udi/UDIBroker/LoginMulti", ReplyAction="*")]
        BTWebAPI.UDIBroker.LoginMultiResponse LoginMulti(BTWebAPI.UDIBroker.LoginMultiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fis.it.udi/UDIBroker/LoginMulti", ReplyAction="*")]
        System.Threading.Tasks.Task<BTWebAPI.UDIBroker.LoginMultiResponse> LoginMultiAsync(BTWebAPI.UDIBroker.LoginMultiRequest request);
        
        // CODEGEN: Generating message contract since element name AccountNo from namespace http://fis.it.udi/UDIBroker is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://fis.it.udi/UDIBroker/LookupInfoByAccountNumber", ReplyAction="*")]
        BTWebAPI.UDIBroker.LookupInfoByAccountNumberResponse LookupInfoByAccountNumber(BTWebAPI.UDIBroker.LookupInfoByAccountNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fis.it.udi/UDIBroker/LookupInfoByAccountNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<BTWebAPI.UDIBroker.LookupInfoByAccountNumberResponse> LookupInfoByAccountNumberAsync(BTWebAPI.UDIBroker.LookupInfoByAccountNumberRequest request);
        
        // CODEGEN: Generating message contract since element name SecurityToken from namespace http://fis.it.udi/UDIBroker is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://fis.it.udi/UDIBroker/Logout", ReplyAction="*")]
        BTWebAPI.UDIBroker.LogoutResponse Logout(BTWebAPI.UDIBroker.LogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fis.it.udi/UDIBroker/Logout", ReplyAction="*")]
        System.Threading.Tasks.Task<BTWebAPI.UDIBroker.LogoutResponse> LogoutAsync(BTWebAPI.UDIBroker.LogoutRequest request);
        
        // CODEGEN: Generating message contract since element name Criteria from namespace http://fis.it.udi/UDIBroker is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://fis.it.udi/UDIBroker/Search", ReplyAction="*")]
        BTWebAPI.UDIBroker.SearchResponse Search(BTWebAPI.UDIBroker.SearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fis.it.udi/UDIBroker/Search", ReplyAction="*")]
        System.Threading.Tasks.Task<BTWebAPI.UDIBroker.SearchResponse> SearchAsync(BTWebAPI.UDIBroker.SearchRequest request);
        
        // CODEGEN: Generating message contract since element name Criteria from namespace http://fis.it.udi/UDIBroker is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://fis.it.udi/UDIBroker/NameSearch", ReplyAction="*")]
        BTWebAPI.UDIBroker.NameSearchResponse NameSearch(BTWebAPI.UDIBroker.NameSearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fis.it.udi/UDIBroker/NameSearch", ReplyAction="*")]
        System.Threading.Tasks.Task<BTWebAPI.UDIBroker.NameSearchResponse> NameSearchAsync(BTWebAPI.UDIBroker.NameSearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fis.it.udi/UDIBroker/HealthCheck", ReplyAction="*")]
        bool HealthCheck();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fis.it.udi/UDIBroker/HealthCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> HealthCheckAsync();
        
        // CODEGEN: Generating message contract since element name Transaction from namespace http://fis.it.udi/UDIBroker is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://fis.it.udi/UDIBroker/DirectToPlatform", ReplyAction="*")]
        BTWebAPI.UDIBroker.DirectToPlatformResponse DirectToPlatform(BTWebAPI.UDIBroker.DirectToPlatformRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fis.it.udi/UDIBroker/DirectToPlatform", ReplyAction="*")]
        System.Threading.Tasks.Task<BTWebAPI.UDIBroker.DirectToPlatformResponse> DirectToPlatformAsync(BTWebAPI.UDIBroker.DirectToPlatformRequest request);
        
        // CODEGEN: Generating message contract since element name Transaction from namespace http://fis.it.udi/UDIBroker is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://fis.it.udi/UDIBroker/BrokeredToken", ReplyAction="*")]
        BTWebAPI.UDIBroker.BrokeredTokenResponse BrokeredToken(BTWebAPI.UDIBroker.BrokeredTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fis.it.udi/UDIBroker/BrokeredToken", ReplyAction="*")]
        System.Threading.Tasks.Task<BTWebAPI.UDIBroker.BrokeredTokenResponse> BrokeredTokenAsync(BTWebAPI.UDIBroker.BrokeredTokenRequest request);
        
        // CODEGEN: Generating message contract since element name transaction from namespace http://fis.it.udi/UDIBroker is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://fis.it.udi/UDIBroker/ProcessByCorp", ReplyAction="*")]
        BTWebAPI.UDIBroker.ProcessByCorpResponse ProcessByCorp(BTWebAPI.UDIBroker.ProcessByCorpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fis.it.udi/UDIBroker/ProcessByCorp", ReplyAction="*")]
        System.Threading.Tasks.Task<BTWebAPI.UDIBroker.ProcessByCorpResponse> ProcessByCorpAsync(BTWebAPI.UDIBroker.ProcessByCorpRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessByAcctRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessByAcct", Namespace="http://fis.it.udi/UDIBroker", Order=0)]
        public BTWebAPI.UDIBroker.ProcessByAcctRequestBody Body;
        
        public ProcessByAcctRequest() {
        }
        
        public ProcessByAcctRequest(BTWebAPI.UDIBroker.ProcessByAcctRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fis.it.udi/UDIBroker")]
    public partial class ProcessByAcctRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string transaction;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AccountNo;
        
        public ProcessByAcctRequestBody() {
        }
        
        public ProcessByAcctRequestBody(string transaction, string AccountNo) {
            this.transaction = transaction;
            this.AccountNo = AccountNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessByAcctResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessByAcctResponse", Namespace="http://fis.it.udi/UDIBroker", Order=0)]
        public BTWebAPI.UDIBroker.ProcessByAcctResponseBody Body;
        
        public ProcessByAcctResponse() {
        }
        
        public ProcessByAcctResponse(BTWebAPI.UDIBroker.ProcessByAcctResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fis.it.udi/UDIBroker")]
    public partial class ProcessByAcctResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ProcessByAcctResult;
        
        public ProcessByAcctResponseBody() {
        }
        
        public ProcessByAcctResponseBody(string ProcessByAcctResult) {
            this.ProcessByAcctResult = ProcessByAcctResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessByBinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessByBin", Namespace="http://fis.it.udi/UDIBroker", Order=0)]
        public BTWebAPI.UDIBroker.ProcessByBinRequestBody Body;
        
        public ProcessByBinRequest() {
        }
        
        public ProcessByBinRequest(BTWebAPI.UDIBroker.ProcessByBinRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fis.it.udi/UDIBroker")]
    public partial class ProcessByBinRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string transaction;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BinNo;
        
        public ProcessByBinRequestBody() {
        }
        
        public ProcessByBinRequestBody(string transaction, string BinNo) {
            this.transaction = transaction;
            this.BinNo = BinNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessByBinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessByBinResponse", Namespace="http://fis.it.udi/UDIBroker", Order=0)]
        public BTWebAPI.UDIBroker.ProcessByBinResponseBody Body;
        
        public ProcessByBinResponse() {
        }
        
        public ProcessByBinResponse(BTWebAPI.UDIBroker.ProcessByBinResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fis.it.udi/UDIBroker")]
    public partial class ProcessByBinResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ProcessByBinResult;
        
        public ProcessByBinResponseBody() {
        }
        
        public ProcessByBinResponseBody(string ProcessByBinResult) {
            this.ProcessByBinResult = ProcessByBinResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://fis.it.udi/UDIBroker", Order=0)]
        public BTWebAPI.UDIBroker.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(BTWebAPI.UDIBroker.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fis.it.udi/UDIBroker")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Credentials;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string Credentials) {
            this.Credentials = Credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://fis.it.udi/UDIBroker", Order=0)]
        public BTWebAPI.UDIBroker.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(BTWebAPI.UDIBroker.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fis.it.udi/UDIBroker")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginMultiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginMulti", Namespace="http://fis.it.udi/UDIBroker", Order=0)]
        public BTWebAPI.UDIBroker.LoginMultiRequestBody Body;
        
        public LoginMultiRequest() {
        }
        
        public LoginMultiRequest(BTWebAPI.UDIBroker.LoginMultiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fis.it.udi/UDIBroker")]
    public partial class LoginMultiRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Credentials;
        
        public LoginMultiRequestBody() {
        }
        
        public LoginMultiRequestBody(string Credentials) {
            this.Credentials = Credentials;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginMultiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginMultiResponse", Namespace="http://fis.it.udi/UDIBroker", Order=0)]
        public BTWebAPI.UDIBroker.LoginMultiResponseBody Body;
        
        public LoginMultiResponse() {
        }
        
        public LoginMultiResponse(BTWebAPI.UDIBroker.LoginMultiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fis.it.udi/UDIBroker")]
    public partial class LoginMultiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginMultiResult;
        
        public LoginMultiResponseBody() {
        }
        
        public LoginMultiResponseBody(string LoginMultiResult) {
            this.LoginMultiResult = LoginMultiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LookupInfoByAccountNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LookupInfoByAccountNumber", Namespace="http://fis.it.udi/UDIBroker", Order=0)]
        public BTWebAPI.UDIBroker.LookupInfoByAccountNumberRequestBody Body;
        
        public LookupInfoByAccountNumberRequest() {
        }
        
        public LookupInfoByAccountNumberRequest(BTWebAPI.UDIBroker.LookupInfoByAccountNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fis.it.udi/UDIBroker")]
    public partial class LookupInfoByAccountNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AccountNo;
        
        public LookupInfoByAccountNumberRequestBody() {
        }
        
        public LookupInfoByAccountNumberRequestBody(string AccountNo) {
            this.AccountNo = AccountNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LookupInfoByAccountNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LookupInfoByAccountNumberResponse", Namespace="http://fis.it.udi/UDIBroker", Order=0)]
        public BTWebAPI.UDIBroker.LookupInfoByAccountNumberResponseBody Body;
        
        public LookupInfoByAccountNumberResponse() {
        }
        
        public LookupInfoByAccountNumberResponse(BTWebAPI.UDIBroker.LookupInfoByAccountNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fis.it.udi/UDIBroker")]
    public partial class LookupInfoByAccountNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LookupInfoByAccountNumberResult;
        
        public LookupInfoByAccountNumberResponseBody() {
        }
        
        public LookupInfoByAccountNumberResponseBody(string LookupInfoByAccountNumberResult) {
            this.LookupInfoByAccountNumberResult = LookupInfoByAccountNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Logout", Namespace="http://fis.it.udi/UDIBroker", Order=0)]
        public BTWebAPI.UDIBroker.LogoutRequestBody Body;
        
        public LogoutRequest() {
        }
        
        public LogoutRequest(BTWebAPI.UDIBroker.LogoutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fis.it.udi/UDIBroker")]
    public partial class LogoutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SecurityToken;
        
        public LogoutRequestBody() {
        }
        
        public LogoutRequestBody(string SecurityToken) {
            this.SecurityToken = SecurityToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoutResponse", Namespace="http://fis.it.udi/UDIBroker", Order=0)]
        public BTWebAPI.UDIBroker.LogoutResponseBody Body;
        
        public LogoutResponse() {
        }
        
        public LogoutResponse(BTWebAPI.UDIBroker.LogoutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fis.it.udi/UDIBroker")]
    public partial class LogoutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LogoutResult;
        
        public LogoutResponseBody() {
        }
        
        public LogoutResponseBody(string LogoutResult) {
            this.LogoutResult = LogoutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Search", Namespace="http://fis.it.udi/UDIBroker", Order=0)]
        public BTWebAPI.UDIBroker.SearchRequestBody Body;
        
        public SearchRequest() {
        }
        
        public SearchRequest(BTWebAPI.UDIBroker.SearchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fis.it.udi/UDIBroker")]
    public partial class SearchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Criteria;
        
        public SearchRequestBody() {
        }
        
        public SearchRequestBody(string Criteria) {
            this.Criteria = Criteria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchResponse", Namespace="http://fis.it.udi/UDIBroker", Order=0)]
        public BTWebAPI.UDIBroker.SearchResponseBody Body;
        
        public SearchResponse() {
        }
        
        public SearchResponse(BTWebAPI.UDIBroker.SearchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fis.it.udi/UDIBroker")]
    public partial class SearchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SearchResult;
        
        public SearchResponseBody() {
        }
        
        public SearchResponseBody(string SearchResult) {
            this.SearchResult = SearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NameSearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NameSearch", Namespace="http://fis.it.udi/UDIBroker", Order=0)]
        public BTWebAPI.UDIBroker.NameSearchRequestBody Body;
        
        public NameSearchRequest() {
        }
        
        public NameSearchRequest(BTWebAPI.UDIBroker.NameSearchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fis.it.udi/UDIBroker")]
    public partial class NameSearchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Criteria;
        
        public NameSearchRequestBody() {
        }
        
        public NameSearchRequestBody(string Criteria) {
            this.Criteria = Criteria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NameSearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NameSearchResponse", Namespace="http://fis.it.udi/UDIBroker", Order=0)]
        public BTWebAPI.UDIBroker.NameSearchResponseBody Body;
        
        public NameSearchResponse() {
        }
        
        public NameSearchResponse(BTWebAPI.UDIBroker.NameSearchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fis.it.udi/UDIBroker")]
    public partial class NameSearchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NameSearchResult;
        
        public NameSearchResponseBody() {
        }
        
        public NameSearchResponseBody(string NameSearchResult) {
            this.NameSearchResult = NameSearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DirectToPlatformRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DirectToPlatform", Namespace="http://fis.it.udi/UDIBroker", Order=0)]
        public BTWebAPI.UDIBroker.DirectToPlatformRequestBody Body;
        
        public DirectToPlatformRequest() {
        }
        
        public DirectToPlatformRequest(BTWebAPI.UDIBroker.DirectToPlatformRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fis.it.udi/UDIBroker")]
    public partial class DirectToPlatformRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Transaction;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SysCode;
        
        public DirectToPlatformRequestBody() {
        }
        
        public DirectToPlatformRequestBody(string Transaction, string SysCode) {
            this.Transaction = Transaction;
            this.SysCode = SysCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DirectToPlatformResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DirectToPlatformResponse", Namespace="http://fis.it.udi/UDIBroker", Order=0)]
        public BTWebAPI.UDIBroker.DirectToPlatformResponseBody Body;
        
        public DirectToPlatformResponse() {
        }
        
        public DirectToPlatformResponse(BTWebAPI.UDIBroker.DirectToPlatformResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fis.it.udi/UDIBroker")]
    public partial class DirectToPlatformResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DirectToPlatformResult;
        
        public DirectToPlatformResponseBody() {
        }
        
        public DirectToPlatformResponseBody(string DirectToPlatformResult) {
            this.DirectToPlatformResult = DirectToPlatformResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BrokeredTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BrokeredToken", Namespace="http://fis.it.udi/UDIBroker", Order=0)]
        public BTWebAPI.UDIBroker.BrokeredTokenRequestBody Body;
        
        public BrokeredTokenRequest() {
        }
        
        public BrokeredTokenRequest(BTWebAPI.UDIBroker.BrokeredTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fis.it.udi/UDIBroker")]
    public partial class BrokeredTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Transaction;
        
        public BrokeredTokenRequestBody() {
        }
        
        public BrokeredTokenRequestBody(string Transaction) {
            this.Transaction = Transaction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BrokeredTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BrokeredTokenResponse", Namespace="http://fis.it.udi/UDIBroker", Order=0)]
        public BTWebAPI.UDIBroker.BrokeredTokenResponseBody Body;
        
        public BrokeredTokenResponse() {
        }
        
        public BrokeredTokenResponse(BTWebAPI.UDIBroker.BrokeredTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fis.it.udi/UDIBroker")]
    public partial class BrokeredTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BrokeredTokenResult;
        
        public BrokeredTokenResponseBody() {
        }
        
        public BrokeredTokenResponseBody(string BrokeredTokenResult) {
            this.BrokeredTokenResult = BrokeredTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessByCorpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessByCorp", Namespace="http://fis.it.udi/UDIBroker", Order=0)]
        public BTWebAPI.UDIBroker.ProcessByCorpRequestBody Body;
        
        public ProcessByCorpRequest() {
        }
        
        public ProcessByCorpRequest(BTWebAPI.UDIBroker.ProcessByCorpRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fis.it.udi/UDIBroker")]
    public partial class ProcessByCorpRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string transaction;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CorpId;
        
        public ProcessByCorpRequestBody() {
        }
        
        public ProcessByCorpRequestBody(string transaction, string CorpId) {
            this.transaction = transaction;
            this.CorpId = CorpId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessByCorpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessByCorpResponse", Namespace="http://fis.it.udi/UDIBroker", Order=0)]
        public BTWebAPI.UDIBroker.ProcessByCorpResponseBody Body;
        
        public ProcessByCorpResponse() {
        }
        
        public ProcessByCorpResponse(BTWebAPI.UDIBroker.ProcessByCorpResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fis.it.udi/UDIBroker")]
    public partial class ProcessByCorpResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ProcessByCorpResult;
        
        public ProcessByCorpResponseBody() {
        }
        
        public ProcessByCorpResponseBody(string ProcessByCorpResult) {
            this.ProcessByCorpResult = ProcessByCorpResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsBinRoutingSoapChannel : BTWebAPI.UDIBroker.wsBinRoutingSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsBinRoutingSoapClient : System.ServiceModel.ClientBase<BTWebAPI.UDIBroker.wsBinRoutingSoap>, BTWebAPI.UDIBroker.wsBinRoutingSoap {
        
        public wsBinRoutingSoapClient() {
        }
        
        public wsBinRoutingSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsBinRoutingSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsBinRoutingSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsBinRoutingSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BTWebAPI.UDIBroker.ProcessByAcctResponse BTWebAPI.UDIBroker.wsBinRoutingSoap.ProcessByAcct(BTWebAPI.UDIBroker.ProcessByAcctRequest request) {
            return base.Channel.ProcessByAcct(request);
        }
        
        public string ProcessByAcct(string transaction, string AccountNo) {
            BTWebAPI.UDIBroker.ProcessByAcctRequest inValue = new BTWebAPI.UDIBroker.ProcessByAcctRequest();
            inValue.Body = new BTWebAPI.UDIBroker.ProcessByAcctRequestBody();
            inValue.Body.transaction = transaction;
            inValue.Body.AccountNo = AccountNo;
            BTWebAPI.UDIBroker.ProcessByAcctResponse retVal = ((BTWebAPI.UDIBroker.wsBinRoutingSoap)(this)).ProcessByAcct(inValue);
            return retVal.Body.ProcessByAcctResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BTWebAPI.UDIBroker.ProcessByAcctResponse> BTWebAPI.UDIBroker.wsBinRoutingSoap.ProcessByAcctAsync(BTWebAPI.UDIBroker.ProcessByAcctRequest request) {
            return base.Channel.ProcessByAcctAsync(request);
        }
        
        public System.Threading.Tasks.Task<BTWebAPI.UDIBroker.ProcessByAcctResponse> ProcessByAcctAsync(string transaction, string AccountNo) {
            BTWebAPI.UDIBroker.ProcessByAcctRequest inValue = new BTWebAPI.UDIBroker.ProcessByAcctRequest();
            inValue.Body = new BTWebAPI.UDIBroker.ProcessByAcctRequestBody();
            inValue.Body.transaction = transaction;
            inValue.Body.AccountNo = AccountNo;
            return ((BTWebAPI.UDIBroker.wsBinRoutingSoap)(this)).ProcessByAcctAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BTWebAPI.UDIBroker.ProcessByBinResponse BTWebAPI.UDIBroker.wsBinRoutingSoap.ProcessByBin(BTWebAPI.UDIBroker.ProcessByBinRequest request) {
            return base.Channel.ProcessByBin(request);
        }
        
        public string ProcessByBin(string transaction, string BinNo) {
            BTWebAPI.UDIBroker.ProcessByBinRequest inValue = new BTWebAPI.UDIBroker.ProcessByBinRequest();
            inValue.Body = new BTWebAPI.UDIBroker.ProcessByBinRequestBody();
            inValue.Body.transaction = transaction;
            inValue.Body.BinNo = BinNo;
            BTWebAPI.UDIBroker.ProcessByBinResponse retVal = ((BTWebAPI.UDIBroker.wsBinRoutingSoap)(this)).ProcessByBin(inValue);
            return retVal.Body.ProcessByBinResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BTWebAPI.UDIBroker.ProcessByBinResponse> BTWebAPI.UDIBroker.wsBinRoutingSoap.ProcessByBinAsync(BTWebAPI.UDIBroker.ProcessByBinRequest request) {
            return base.Channel.ProcessByBinAsync(request);
        }
        
        public System.Threading.Tasks.Task<BTWebAPI.UDIBroker.ProcessByBinResponse> ProcessByBinAsync(string transaction, string BinNo) {
            BTWebAPI.UDIBroker.ProcessByBinRequest inValue = new BTWebAPI.UDIBroker.ProcessByBinRequest();
            inValue.Body = new BTWebAPI.UDIBroker.ProcessByBinRequestBody();
            inValue.Body.transaction = transaction;
            inValue.Body.BinNo = BinNo;
            return ((BTWebAPI.UDIBroker.wsBinRoutingSoap)(this)).ProcessByBinAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BTWebAPI.UDIBroker.LoginResponse BTWebAPI.UDIBroker.wsBinRoutingSoap.Login(BTWebAPI.UDIBroker.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string Credentials) {
            BTWebAPI.UDIBroker.LoginRequest inValue = new BTWebAPI.UDIBroker.LoginRequest();
            inValue.Body = new BTWebAPI.UDIBroker.LoginRequestBody();
            inValue.Body.Credentials = Credentials;
            BTWebAPI.UDIBroker.LoginResponse retVal = ((BTWebAPI.UDIBroker.wsBinRoutingSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BTWebAPI.UDIBroker.LoginResponse> BTWebAPI.UDIBroker.wsBinRoutingSoap.LoginAsync(BTWebAPI.UDIBroker.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<BTWebAPI.UDIBroker.LoginResponse> LoginAsync(string Credentials) {
            BTWebAPI.UDIBroker.LoginRequest inValue = new BTWebAPI.UDIBroker.LoginRequest();
            inValue.Body = new BTWebAPI.UDIBroker.LoginRequestBody();
            inValue.Body.Credentials = Credentials;
            return ((BTWebAPI.UDIBroker.wsBinRoutingSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BTWebAPI.UDIBroker.LoginMultiResponse BTWebAPI.UDIBroker.wsBinRoutingSoap.LoginMulti(BTWebAPI.UDIBroker.LoginMultiRequest request) {
            return base.Channel.LoginMulti(request);
        }
        
        public string LoginMulti(string Credentials) {
            BTWebAPI.UDIBroker.LoginMultiRequest inValue = new BTWebAPI.UDIBroker.LoginMultiRequest();
            inValue.Body = new BTWebAPI.UDIBroker.LoginMultiRequestBody();
            inValue.Body.Credentials = Credentials;
            BTWebAPI.UDIBroker.LoginMultiResponse retVal = ((BTWebAPI.UDIBroker.wsBinRoutingSoap)(this)).LoginMulti(inValue);
            return retVal.Body.LoginMultiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BTWebAPI.UDIBroker.LoginMultiResponse> BTWebAPI.UDIBroker.wsBinRoutingSoap.LoginMultiAsync(BTWebAPI.UDIBroker.LoginMultiRequest request) {
            return base.Channel.LoginMultiAsync(request);
        }
        
        public System.Threading.Tasks.Task<BTWebAPI.UDIBroker.LoginMultiResponse> LoginMultiAsync(string Credentials) {
            BTWebAPI.UDIBroker.LoginMultiRequest inValue = new BTWebAPI.UDIBroker.LoginMultiRequest();
            inValue.Body = new BTWebAPI.UDIBroker.LoginMultiRequestBody();
            inValue.Body.Credentials = Credentials;
            return ((BTWebAPI.UDIBroker.wsBinRoutingSoap)(this)).LoginMultiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BTWebAPI.UDIBroker.LookupInfoByAccountNumberResponse BTWebAPI.UDIBroker.wsBinRoutingSoap.LookupInfoByAccountNumber(BTWebAPI.UDIBroker.LookupInfoByAccountNumberRequest request) {
            return base.Channel.LookupInfoByAccountNumber(request);
        }
        
        public string LookupInfoByAccountNumber(string AccountNo) {
            BTWebAPI.UDIBroker.LookupInfoByAccountNumberRequest inValue = new BTWebAPI.UDIBroker.LookupInfoByAccountNumberRequest();
            inValue.Body = new BTWebAPI.UDIBroker.LookupInfoByAccountNumberRequestBody();
            inValue.Body.AccountNo = AccountNo;
            BTWebAPI.UDIBroker.LookupInfoByAccountNumberResponse retVal = ((BTWebAPI.UDIBroker.wsBinRoutingSoap)(this)).LookupInfoByAccountNumber(inValue);
            return retVal.Body.LookupInfoByAccountNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BTWebAPI.UDIBroker.LookupInfoByAccountNumberResponse> BTWebAPI.UDIBroker.wsBinRoutingSoap.LookupInfoByAccountNumberAsync(BTWebAPI.UDIBroker.LookupInfoByAccountNumberRequest request) {
            return base.Channel.LookupInfoByAccountNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<BTWebAPI.UDIBroker.LookupInfoByAccountNumberResponse> LookupInfoByAccountNumberAsync(string AccountNo) {
            BTWebAPI.UDIBroker.LookupInfoByAccountNumberRequest inValue = new BTWebAPI.UDIBroker.LookupInfoByAccountNumberRequest();
            inValue.Body = new BTWebAPI.UDIBroker.LookupInfoByAccountNumberRequestBody();
            inValue.Body.AccountNo = AccountNo;
            return ((BTWebAPI.UDIBroker.wsBinRoutingSoap)(this)).LookupInfoByAccountNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BTWebAPI.UDIBroker.LogoutResponse BTWebAPI.UDIBroker.wsBinRoutingSoap.Logout(BTWebAPI.UDIBroker.LogoutRequest request) {
            return base.Channel.Logout(request);
        }
        
        public string Logout(string SecurityToken) {
            BTWebAPI.UDIBroker.LogoutRequest inValue = new BTWebAPI.UDIBroker.LogoutRequest();
            inValue.Body = new BTWebAPI.UDIBroker.LogoutRequestBody();
            inValue.Body.SecurityToken = SecurityToken;
            BTWebAPI.UDIBroker.LogoutResponse retVal = ((BTWebAPI.UDIBroker.wsBinRoutingSoap)(this)).Logout(inValue);
            return retVal.Body.LogoutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BTWebAPI.UDIBroker.LogoutResponse> BTWebAPI.UDIBroker.wsBinRoutingSoap.LogoutAsync(BTWebAPI.UDIBroker.LogoutRequest request) {
            return base.Channel.LogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<BTWebAPI.UDIBroker.LogoutResponse> LogoutAsync(string SecurityToken) {
            BTWebAPI.UDIBroker.LogoutRequest inValue = new BTWebAPI.UDIBroker.LogoutRequest();
            inValue.Body = new BTWebAPI.UDIBroker.LogoutRequestBody();
            inValue.Body.SecurityToken = SecurityToken;
            return ((BTWebAPI.UDIBroker.wsBinRoutingSoap)(this)).LogoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BTWebAPI.UDIBroker.SearchResponse BTWebAPI.UDIBroker.wsBinRoutingSoap.Search(BTWebAPI.UDIBroker.SearchRequest request) {
            return base.Channel.Search(request);
        }
        
        public string Search(string Criteria) {
            BTWebAPI.UDIBroker.SearchRequest inValue = new BTWebAPI.UDIBroker.SearchRequest();
            inValue.Body = new BTWebAPI.UDIBroker.SearchRequestBody();
            inValue.Body.Criteria = Criteria;
            BTWebAPI.UDIBroker.SearchResponse retVal = ((BTWebAPI.UDIBroker.wsBinRoutingSoap)(this)).Search(inValue);
            return retVal.Body.SearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BTWebAPI.UDIBroker.SearchResponse> BTWebAPI.UDIBroker.wsBinRoutingSoap.SearchAsync(BTWebAPI.UDIBroker.SearchRequest request) {
            return base.Channel.SearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<BTWebAPI.UDIBroker.SearchResponse> SearchAsync(string Criteria) {
            BTWebAPI.UDIBroker.SearchRequest inValue = new BTWebAPI.UDIBroker.SearchRequest();
            inValue.Body = new BTWebAPI.UDIBroker.SearchRequestBody();
            inValue.Body.Criteria = Criteria;
            return ((BTWebAPI.UDIBroker.wsBinRoutingSoap)(this)).SearchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BTWebAPI.UDIBroker.NameSearchResponse BTWebAPI.UDIBroker.wsBinRoutingSoap.NameSearch(BTWebAPI.UDIBroker.NameSearchRequest request) {
            return base.Channel.NameSearch(request);
        }
        
        public string NameSearch(string Criteria) {
            BTWebAPI.UDIBroker.NameSearchRequest inValue = new BTWebAPI.UDIBroker.NameSearchRequest();
            inValue.Body = new BTWebAPI.UDIBroker.NameSearchRequestBody();
            inValue.Body.Criteria = Criteria;
            BTWebAPI.UDIBroker.NameSearchResponse retVal = ((BTWebAPI.UDIBroker.wsBinRoutingSoap)(this)).NameSearch(inValue);
            return retVal.Body.NameSearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BTWebAPI.UDIBroker.NameSearchResponse> BTWebAPI.UDIBroker.wsBinRoutingSoap.NameSearchAsync(BTWebAPI.UDIBroker.NameSearchRequest request) {
            return base.Channel.NameSearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<BTWebAPI.UDIBroker.NameSearchResponse> NameSearchAsync(string Criteria) {
            BTWebAPI.UDIBroker.NameSearchRequest inValue = new BTWebAPI.UDIBroker.NameSearchRequest();
            inValue.Body = new BTWebAPI.UDIBroker.NameSearchRequestBody();
            inValue.Body.Criteria = Criteria;
            return ((BTWebAPI.UDIBroker.wsBinRoutingSoap)(this)).NameSearchAsync(inValue);
        }
        
        public bool HealthCheck() {
            return base.Channel.HealthCheck();
        }
        
        public System.Threading.Tasks.Task<bool> HealthCheckAsync() {
            return base.Channel.HealthCheckAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BTWebAPI.UDIBroker.DirectToPlatformResponse BTWebAPI.UDIBroker.wsBinRoutingSoap.DirectToPlatform(BTWebAPI.UDIBroker.DirectToPlatformRequest request) {
            return base.Channel.DirectToPlatform(request);
        }
        
        public string DirectToPlatform(string Transaction, string SysCode) {
            BTWebAPI.UDIBroker.DirectToPlatformRequest inValue = new BTWebAPI.UDIBroker.DirectToPlatformRequest();
            inValue.Body = new BTWebAPI.UDIBroker.DirectToPlatformRequestBody();
            inValue.Body.Transaction = Transaction;
            inValue.Body.SysCode = SysCode;
            BTWebAPI.UDIBroker.DirectToPlatformResponse retVal = ((BTWebAPI.UDIBroker.wsBinRoutingSoap)(this)).DirectToPlatform(inValue);
            return retVal.Body.DirectToPlatformResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BTWebAPI.UDIBroker.DirectToPlatformResponse> BTWebAPI.UDIBroker.wsBinRoutingSoap.DirectToPlatformAsync(BTWebAPI.UDIBroker.DirectToPlatformRequest request) {
            return base.Channel.DirectToPlatformAsync(request);
        }
        
        public System.Threading.Tasks.Task<BTWebAPI.UDIBroker.DirectToPlatformResponse> DirectToPlatformAsync(string Transaction, string SysCode) {
            BTWebAPI.UDIBroker.DirectToPlatformRequest inValue = new BTWebAPI.UDIBroker.DirectToPlatformRequest();
            inValue.Body = new BTWebAPI.UDIBroker.DirectToPlatformRequestBody();
            inValue.Body.Transaction = Transaction;
            inValue.Body.SysCode = SysCode;
            return ((BTWebAPI.UDIBroker.wsBinRoutingSoap)(this)).DirectToPlatformAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BTWebAPI.UDIBroker.BrokeredTokenResponse BTWebAPI.UDIBroker.wsBinRoutingSoap.BrokeredToken(BTWebAPI.UDIBroker.BrokeredTokenRequest request) {
            return base.Channel.BrokeredToken(request);
        }
        
        public string BrokeredToken(string Transaction) {
            BTWebAPI.UDIBroker.BrokeredTokenRequest inValue = new BTWebAPI.UDIBroker.BrokeredTokenRequest();
            inValue.Body = new BTWebAPI.UDIBroker.BrokeredTokenRequestBody();
            inValue.Body.Transaction = Transaction;
            BTWebAPI.UDIBroker.BrokeredTokenResponse retVal = ((BTWebAPI.UDIBroker.wsBinRoutingSoap)(this)).BrokeredToken(inValue);
            return retVal.Body.BrokeredTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BTWebAPI.UDIBroker.BrokeredTokenResponse> BTWebAPI.UDIBroker.wsBinRoutingSoap.BrokeredTokenAsync(BTWebAPI.UDIBroker.BrokeredTokenRequest request) {
            return base.Channel.BrokeredTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<BTWebAPI.UDIBroker.BrokeredTokenResponse> BrokeredTokenAsync(string Transaction) {
            BTWebAPI.UDIBroker.BrokeredTokenRequest inValue = new BTWebAPI.UDIBroker.BrokeredTokenRequest();
            inValue.Body = new BTWebAPI.UDIBroker.BrokeredTokenRequestBody();
            inValue.Body.Transaction = Transaction;
            return ((BTWebAPI.UDIBroker.wsBinRoutingSoap)(this)).BrokeredTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BTWebAPI.UDIBroker.ProcessByCorpResponse BTWebAPI.UDIBroker.wsBinRoutingSoap.ProcessByCorp(BTWebAPI.UDIBroker.ProcessByCorpRequest request) {
            return base.Channel.ProcessByCorp(request);
        }
        
        public string ProcessByCorp(string transaction, string CorpId) {
            BTWebAPI.UDIBroker.ProcessByCorpRequest inValue = new BTWebAPI.UDIBroker.ProcessByCorpRequest();
            inValue.Body = new BTWebAPI.UDIBroker.ProcessByCorpRequestBody();
            inValue.Body.transaction = transaction;
            inValue.Body.CorpId = CorpId;
            BTWebAPI.UDIBroker.ProcessByCorpResponse retVal = ((BTWebAPI.UDIBroker.wsBinRoutingSoap)(this)).ProcessByCorp(inValue);
            return retVal.Body.ProcessByCorpResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BTWebAPI.UDIBroker.ProcessByCorpResponse> BTWebAPI.UDIBroker.wsBinRoutingSoap.ProcessByCorpAsync(BTWebAPI.UDIBroker.ProcessByCorpRequest request) {
            return base.Channel.ProcessByCorpAsync(request);
        }
        
        public System.Threading.Tasks.Task<BTWebAPI.UDIBroker.ProcessByCorpResponse> ProcessByCorpAsync(string transaction, string CorpId) {
            BTWebAPI.UDIBroker.ProcessByCorpRequest inValue = new BTWebAPI.UDIBroker.ProcessByCorpRequest();
            inValue.Body = new BTWebAPI.UDIBroker.ProcessByCorpRequestBody();
            inValue.Body.transaction = transaction;
            inValue.Body.CorpId = CorpId;
            return ((BTWebAPI.UDIBroker.wsBinRoutingSoap)(this)).ProcessByCorpAsync(inValue);
        }
    }
}
